apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-arch-2021-03-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hw02-crud-app
  template:
    metadata:
      labels:
        app: hw02-crud-app
    spec:
      containers:
        - name: hw02-crud
          image: xamejleoh/hw02-crud:0.1
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 80
          envFrom:
            - configMapRef:
                name: ms-arch-2021-03-config
            - secretRef:
                name: ms-arch-2021-03-secret



