apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-arch-2021-03-config
data:
  spring.datasource.url: jdbc:postgresql://postgres:5432/myapp
  ms.order.url.cancel.payment: "http://arch.homework/otusapp/makhanov/payment/"
  ms.order.url.cancel.reserve: "http://arch.homework/otusapp/makhanov/warehouse/"
  ms.order.url.order.finish: "http://arch.homework/otusapp/makhanov/order/finish/"
  ms.order.url.cancel.order: "http://arch.homework/otusapp/makhanov/order/"

---
apiVersion: v1
kind: Secret
metadata:
  name: ms-arch-2021-03-secret
type: Opaque
data:
  spring.datasource.username: bXl1c2Vy
  spring.datasource.password: cGFzc3dk