replicaCount: 2

image:
  repository: hw03-prometheus

service:
  type: NodePort
  port: 9000

externalPostgresql:
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  postgresqlHost: "postgres"
  postgresqlPort: "5432"

metrics:
  serviceMonitor:
    enabled: true

ingressName: ms-arch-2021-03-ingress
ingressHost: arch.homework
ingressServiceName: hw03-prometheus-ms-arch-2021-03
ingress:
  enabled: true
  hosts:
    - host: arch.homework
      paths: ["/otusapp"]

#ingressName: ms-arch-2021-03-ingress
#ingressHost: arch.homework
#ingressServiceName: hw02-crud-ms-arch-2021-03